# Домашнее задание «Функции и работа с данными»

### Задание №1
Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:

оценка 2 и меньше - низкий рейтинг

оценка 4 и меньше - средний рейтинг

оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class

In [16]:
import pandas as pd
stats = pd.read_csv('ratings.csv')
movies = pd.read_csv('movies.csv')
def rating(row):
    if row <=2:
        return 'низкий рейтинг'
    elif row > 2 and row <= 4 :
        return 'средний рейтинг'
    return 'высокий рейтинг'
stats['class'] = stats['rating'].apply(rating)
joined = stats.merge(movies, on = 'movieId', how = 'left')
joined.head(10)

,userId,movieId,rating,timestamp,class,title,genres
0,1,31,2.5,1260759144,средний рейтинг,Dangerous Minds (1995),Drama
1,1,1029,3.0,1260759179,средний рейтинг,Dumbo (1941),Animation|Children|Drama|Musical
2,1,1061,3.0,1260759182,средний рейтинг,Sleepers (1996),Thriller
3,1,1129,2.0,1260759185,низкий рейтинг,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller
4,1,1172,4.0,1260759205,средний рейтинг,Cinema Paradiso (Nuovo cinema Paradiso) (1989),Drama
5,1,1263,2.0,1260759151,низкий рейтинг,"Deer Hunter, The (1978)",Drama|War
6,1,1287,2.0,1260759187,низкий рейтинг,Ben-Hur (1959),Action|Adventure|Drama
7,1,1293,2.0,1260759148,низкий рейтинг,Gandhi (1982),Drama
8,1,1339,3.5,1260759125,средний рейтинг,Dracula (Bram Stoker's Dracula) (1992),Fantasy|Horror|Romance|Thriller
9,1,1343,2.0,1260759131,низкий рейтинг,Cape Fear (1991),Thriller

### Задание 2
Используем файл keywords.csv.

Необходимо написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определенному региону. Т. е. если поисковый запрос содержит название города региона, то в столбце ‘region’ пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим ‘undefined’.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:

geo_data = {

'Центр': ['москва', 'тула', 'ярославль'],

'Северо-Запад': ['петербург', 'псков', 'мурманск'],

'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

Результат классификации запишите в отдельный столбец region.

In [9]:
import pandas as pd

In [10]:
keywords_df = pd.read_csv('keywords.csv', \
                         sep=',', header=0, encoding='UTF-8')

In [11]:
keywords_df.head()

         keyword     shows
0             вк  64292779
1  одноклассники  63810309
2          порно  41747114
3           ютуб  39995567
4      вконтакте  21014195

In [12]:
geo_data = {
'Центр': ['москва', 'тула', 'ярославль'],
'Северо-Запад': ['петербург', 'псков', 'мурманск'],
'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

In [13]:
def geo_func(keywords):
    for name in geo_data:
        if keywords in geo_data[name]:
                return name
    return "undefined"

In [14]:
keywords_df['region'] = keywords_df['keyword'].apply(geo_func)
keywords_df[keywords_df["region"] != "undefined"]

           keyword   shows          region
1259        москва  153050           Центр
5858   владивосток   43038  Дальний Восток
6075     ярославль   41720           Центр
8977      мурманск   29984    Северо-Запад
9084     хабаровск   29655  Дальний Восток
11222        псков   24885    Северо-Запад
11785         тула   23898           Центр
20823    петербург   14859    Северо-Запад
21445      сахалин   14494  Дальний Восток